### ISSUE TITLE
Warning on ./install script

### ISSUE THREAD

**Issue by ITSoluce** [PmaControl/PmaControl#29]
#1 -> <b>Fichier</b> : /data/www/pmacontrol/application/controller/Install.controller.php <b>Ligne</b> : 207
 <b>Fonction</b> testMySQL
 <b>Classe</b> Install
 <b>Argument 1</b> 127.0.0.1
 <b>Argument 2</b> 3306
 <b>Argument 3</b> root
 <b>Argument 4</b> FFSfrsthtTBN
#2 -> <b>Fichier</b> : /data/www/pmacontrol/application/controller/Install.controller.php <b>Ligne</b> : 112
 <b>Fonction</b> testMysqlServer
 <b>Classe</b> Install
#3 -> <b>Fichier</b> : /data/www/pmacontrol/vendor/glial/glial/Glial/Synapse/Controller.php <b>Ligne</b> : 103
 <b>Fonction</b> index
 <b>Classe</b> Install
 <b>Argument 1</b> 
#4 -> <b>Fichier</b> : /data/www/pmacontrol/vendor/glial/glial/Glial/Synapse/FactoryController.php <b>Ligne</b> : 68
 <b>Fonction</b> getController
 <b>Classe</b> Glial\Synapse\Controller
#5 -> <b>Fichier</b> : /data/www/pmacontrol/vendor/glial/glial/Glial/Bootstrap.php <b>Ligne</b> : 247
 <b>Fonction</b> rootNode
 <b>Classe</b> Glial\Synapse\FactoryController
 <b>Argument 1</b> install
 <b>Argument 2</b> index
 <b>Argument 3</b> 
#6 -> <b>Fichier</b> : /data/www/pmacontrol/application/webroot/index.php <b>Ligne</b> : 102
 <b>Fonction</b> include
 <b>Argument 1</b> /data/www/pmacontrol/vendor/glial/glial/Glial/Bootstrap.php
</td></tr></table></div>

**Comment by Gagmanfr** [comment]
<div style='text-align: left;'><p style='color: rgb(190, 50, 50);'>Probléme informatique - Une exception a été levée :</p>
<table style='display: inline-block;'><tr style='background-color:rgb(240,240,240);'><th style='width: 80px;'>Type</th>
<td style='background-color:rgb(230,230,230);'>E_WARNING (2)</td></tr>
<tr style='background-color:rgb(240,240,240);'><th>Date Heure</th><td style='background-color:rgb(230,230,230);'>2019-02-12 19:00:26</td></tr>
<tr style='background-color:rgb(240,240,240);'><th>Message</th><td style='background-color:rgb(230,230,230);'>fsockopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known</td></tr>
<tr style='background-color:rgb(240,240,240);'><th>Pile</th><td style='background-color:rgb(230,230,230);'>#0 -> <b>Fichier</b> : /data/www/pmacontrol/application/controller/Install.controller.php <b>Ligne</b> : 692
 <b>Fonction</b> fsockopen
 <b>Argument 1</b> *
 <b>Argument 2</b> 3306
 <b>Argument 3</b> 0
 <b>Argument 4</b> 
 <b>Argument 5</b> 30
#1 -> <b>Fichier</b> : /data/www/pmacontrol/application/controller/Install.controller.php <b>Ligne</b> : 175
 <b>Fonction</b> testIpPort
 <b>Classe</b> Install
 <b>Argument 1</b> *
 <b>Argument 2</b> 3306
#2 -> <b>Fichier</b> : /data/www/pmacontrol/application/controller/Install.controller.php <b>Ligne</b> : 112<br> <b>Fonction</b> testMysqlServer
 <b>Classe</b> Install
#3 -> <b>Fichier</b> : /data/www/pmacontrol/vendor/glial/glial/Glial/Synapse/Controller.php <b>Ligne</b> : 103
 <b>Fonction</b> index
 <b>Classe</b> Install
 <b>Argument 1</b> 
#4 -> <b>Fichier</b> : /data/www/pmacontrol/vendor/glial/glial/Glial/Synapse/FactoryController.php <b>Ligne</b> : 68
 <b>Fonction</b> getController
 <b>Classe</b> Glial\Synapse\Controller
#5 -> <b>Fichier</b> : /data/www/pmacontrol/vendor/glial/glial/Glial/Bootstrap.php <b>Ligne</b> : 247
 <b>Fonction</b> rootNode
 <b>Classe</b> Glial\Synapse\FactoryController
 <b>Argument 1</b> install
 <b>Argument 2</b> index
 <b>Argument 3</b> 
#6 -> <b>Fichier</b> : /data/www/pmacontrol/application/webroot/index.php <b>Ligne</b> : 102
 <b>Fonction</b> include
 <b>Argument 1</b> /data/www/pmacontrol/vendor/glial/glial/Glial/Bootstrap.php
</td></tr></table></div>
<div style='text-align: left;'><p style='color: rgb(190, 50, 50);'>Probléme informatique - Une exception a été levée :</p>
<table style='display: inline-block;'><tr style='background-color:rgb(240,240,240);'><th style='width: 80px;'>Type</th>
<td style='background-color:rgb(230,230,230);'>E_WARNING (2)</td></tr>
<tr style='background-color:rgb(240,240,240);'><th>Date Heure</th><td style='background-color:rgb(230,230,230);'>2019-02-12 19:00:26</td></tr>
<tr style='background-color:rgb(240,240,240);'><th>Message</th><td style='background-color:rgb(230,230,230);'>fsockopen(): unable to connect to *:3306 (php_network_getaddresses: getaddrinfo failed: Name or service not known)</td></tr>
<tr style='background-color:rgb(240,240,240);'><th>Pile</th><td style='background-color:rgb(230,230,230);'>#0 -> <b>Fichier</b> : /data/www/pmacontrol/application/controller/Install.controller.php <b>Ligne</b> : 692
 <b>Fonction</b> fsockopen
 <b>Argument 1</b> *
 <b>Argument 2</b> 3306
 <b>Argument 3</b> 0
 <b>Argument 4</b> 
 <b>Argument 5</b> 30<br>#1 -> <b>Fichier</b> : /data/www/pmacontrol/application/controller/Install.controller.php <b>Ligne</b> : 175
 <b>Fonction</b> testIpPort
 <b>Classe</b> Install
 <b>Argument 1</b> *
 <b>Argument 2</b> 3306
#2 -> <b>Fichier</b> : /data/www/pmacontrol/application/controller/Install.controller.php <b>Ligne</b> : 112
 <b>Fonction</b> testMysqlServer
 <b>Classe</b> Install
#3 -> <b>Fichier</b> : /data/www/pmacontrol/vendor/glial/glial/Glial/Synapse/Controller.php <b>Ligne</b> : 103
 <b>Fonction</b> index
 <b>Classe</b> Install<br> <b>Argument 1</b> 
#4 -> <b>Fichier</b> : /data/www/pmacontrol/vendor/glial/glial/Glial/Synapse/FactoryController.php <b>Ligne</b> : 68
 <b>Fonction</b> getController
 <b>Classe</b> Glial\Synapse\Controller
#5 -> <b>Fichier</b> : /data/www/pmacontrol/vendor/glial/glial/Glial/Bootstrap.php <b>Ligne</b> : 247
 <b>Fonction</b> rootNode
 <b>Classe</b> Glial\Synapse\FactoryController
 <b>Argument 1</b> install
 <b>Argument 2</b> index
 <b>Argument 3</b> 
#6 -> <b>Fichier</b> : /data/www/pmacontrol/application/webroot/index.php <b>Ligne</b> : 102
 <b>Fonction</b> include
 <b>Argument 1</b> /data/www/pmacontrol/vendor/glial/glial/Glial/Bootstrap.php
</td></tr></table></div>

**Comment by Esysteme** [comment]
fixed in 1.3.12
