### ISSUE TITLE
install php 7.2 problem ?

### ISSUE THREAD

**Issue by Gagmanfr** [PmaControl/PmaControl#3]
Warning: Illegal string offset 'user_main' in /data/www/pmacontrol/vendor/glial/glial/Glial/Sgbd/Sql/Sql.php on line 472

Notice: Array to string conversion in /data/www/pmacontrol/vendor/glial/glial/Glial/Sgbd/Sql/Sql.php on line 472

Warning: Illegal string offset 'user_main' in /data/www/pmacontrol/vendor/glial/glial/Glial/Sgbd/Sql/Sql.php on line 473

Warning: Illegal string offset 'user_main' in /data/www/pmacontrol/vendor/glial/glial/Glial/Sgbd/Sql/Sql.php on line 238

Warning: Illegal string offset 'field' in /data/www/pmacontrol/vendor/glial/glial/Glial/Sgbd/Sql/Sql.php on line 238

Warning: in_array() expects parameter 2 to be array, string given in /data/www/pmacontrol/vendor/glial/glial/Glial/Sgbd/Sql/Sql.php on line 238

[2018-05-17 17:00:21] SQL : INSERT INTO `user_main` (``) VALUES ('');
Unknown column '' in 'field list'
FILE : /data/www/pmacontrol/application/controller/Install.controller.php LINE : 559
[2018-05-17 17:00:21][ERROR] GLI-031 : Impossible to fine last id inserted in case of insert ignore
CODE ERROR : 0

**Comment by Esysteme** [comment]
fixed in 1.2.6
