### ISSUE TITLE
Backup / Archive : chiffrement en option

### ISSUE THREAD

**Issue by Esysteme** [PmaControl/PmaControl#38]
Afin de simplifier certains traitement, il faudrait une option afin que le chiffrement (pour les données purgé soit optionnel).

* Option à donner au niveau de la purge  (checkbox)

* Tables impacté : 
  * cleaner_main (ajouter is_crypted)
  * archive (ajouter is_crypted)

* Code : 
  * Cleaner.controller.php (pushArchive)
  * Archives.controller.php (load_archive)

**Comment by ITSoluce** [comment]
Et la clé de cryptage, tu la stockes ou ?

**Comment by Esysteme** [comment]
Configuration

Le sam. 18 mai 2019 à 17:16, Renaud PLATEL <notifications@github.com> a
écrit :

**Comment by Esysteme** [comment]
fait !

version : 1.3.11
